# Generated by Django 2.2 on 2020-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201110_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
