# Generated by Django 2.2 on 2020-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik', models.CharField(default='', max_length=20)),
                ('nama', models.CharField(default='', max_length=20)),
                ('alamat', models.CharField(default='', max_length=100)),
                ('telp', models.CharField(default='', max_length=15)),
                ('gambar', models.TextField(default='')),
            ],
        ),
    ]
