# Generated by Django 2.2 on 2020-10-30 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toko', to=settings.AUTH_USER_MODEL),
        ),
    ]
