# Generated by Django 2.2 on 2020-11-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_auto_20201030_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='toko',
            name='nomor_ktp',
            field=models.CharField(default='', max_length=16),
        ),
    ]
