# Generated by Django 2.2 on 2020-11-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_toko_nomor_ktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='toko',
            name='gambar_ktp',
            field=models.TextField(default=''),
        ),
    ]
