# Generated by Django 2.2 on 2020-11-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_toko_gambar_ktp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toko',
            name='gambar_ktp',
        ),
    ]
