# Generated by Django 2.2 on 2021-02-05 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toko', '0007_auto_20201126_0415'),
        ('products', '0002_prod_deskp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=30)),
                ('email', models.TextField(default='', max_length=255)),
                ('alamat', models.TextField(default='', max_length=255)),
                ('no_hp', models.CharField(max_length=30)),
                ('pengiriman', models.CharField(max_length=30)),
                ('provinsi', models.CharField(default='', max_length=30)),
                ('kabupaten', models.CharField(default='', max_length=30)),
                ('kecamatan', models.CharField(default='', max_length=30)),
                ('desa', models.CharField(default='', max_length=30)),
                ('kode_t', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('uniqq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga1', to='sales.Kode')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('resi', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terjual', to='products.Prod')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sama', to='sales.Sale')),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan', to='toko.Toko')),
            ],
        ),
    ]
