# Generated by Django 2.2 on 2020-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='deskp',
            field=models.TextField(default=''),
        ),
    ]
